/** Nội dung trợ giúp chi tiết — người mới chưa biết cũng làm theo được. */

export function buildOwnerHelpText(): string {
  return [
    "📖 HƯỚNG DẪN — CHỦ ĐẠI LÝ",
    "",
    "━━ 1. LẦN ĐẦU DÙNG ━━",
    "• Nhận mã mời dạng GAS-XXXXXXXX từ người cài đặt hệ thống.",
    "• Bấm link mời hoặc gõ trong chat bot:",
    "  /start GAS-XXXXXXXX",
    "• Thấy menu quản trị → bạn đã kích hoạt xong.",
    "",
    "━━ 2. MENU CHÍNH (gõ /menu_admin) ━━",
    "👷 Đội ngũ — quản lý nhân viên, tạo mã mời NV (đang bổ sung).",
    "👤 Khách hàng — thêm/tìm khách, lên đơn, thu nợ.",
    "📊 Thống kê — doanh thu, đơn hàng, **đăng nhập dashboard web**.",
    "⚙️ Cài đặt — giá bình gas, mã mời NV (tạm).",
    "❓ Trợ giúp — đọc hướng dẫn này.",
    "",
    "━━ 3. THÊM KHÁCH MỚI ━━",
    "👤 Khách hàng → ➕ Thêm khách",
    "Gõ đúng format (dùng dấu - ):",
    "Tên - SĐT - Địa chỉ",
    "VD: Quán Phở Hoa - 0901234567 - 123 Lê Lợi",
    "→ Bấm ✅ Lưu.",
    "",
    "━━ 4. LÊN ĐƠN GIAO CHO KHÁCH ━━",
    "👤 Khách hàng → 🏆 Top 10 hoặc 🔍 Tìm khách",
    "→ Chọn tên khách → 📦 Tạo đơn",
    "→ Chọn loại bình (12kg, 45kg…)",
    "→ Nhập số bình (VD: 4)",
    "→ ✅ Xác nhận lên đơn",
    "→ Chọn người giao (chủ hoặc NV).",
    "  · Chỉ có mình bạn → tự gán cho bạn.",
    "  · Nhiều người → chọn NV hoặc để trống để NV tự nhận.",
    "NV được gán sẽ nhận tin trên Telegram.",
    "",
    "━━ 5. THU NỢ KHÁCH ━━",
    "(Chỉ chủ — NV không thu nợ trên bot)",
    "👤 Khách hàng → tìm khách → chi tiết",
    "→ 💵 Thu nợ",
    "Nhập: số tiền + tm hoặc ck",
    "VD: 500000 tm  (tiền mặt)",
    "VD: 300000 ck  (chuyển khoản)",
    "",
    "━━ 6. XEM / HUỶ ĐƠN CHƯA GIAO ━━",
    "📊 Thống kê → 📋 Đơn hàng",
    "→ 📋 Quản lý đơn mở",
    "→ Chọn đơn → có thể huỷ nếu nhập sai.",
    "",
    "━━ 7. MỜI NHÂN VIÊN ━━",
    "⚙️ Cài đặt → 🔗 Mã mời NV (tạm, sau chuyển sang Đội ngũ)",
    "Copy link gửi cho NV → NV bấm link và /start.",
    "Mã hết hạn sau 72 giờ — tạo mã mới nếu cần.",
    "",
    "━━ 8. DASHBOARD WEB (màn hình lớn) ━━",
    "📊 Thống kê → 🌐 Đăng nhập web",
    "Bot gửi link — bấm mở trình duyệt (không dùng trong Telegram).",
    "Link dùng 1 lần, hết hạn ~5 phút.",
    "Trên web: sửa khách, báo cáo, đội ngũ chi tiết.",
    "",
    "━━ 9. LỆNH NHANH ━━",
    "/menu_admin — mở menu quản trị",
    "/no tên hoặc SĐT — tra nợ nhanh",
    "/help — xem lại hướng dẫn",
    "(Tuỳ chọn: /weblogin — cùng chức năng với Thống kê → Đăng nhập web)",
  ].join("\n");
}

export function buildEmployeeHelpText(): string {
  return [
    "📖 HƯỚNG DẪN — NHÂN VIÊN GIAO HÀNG",
    "",
    "━━ 1. LẦN ĐẦU DÙNG ━━",
    "• Chủ đại lý gửi link mời (hoặc mã GAS-…).",
    "• Bấm link → Telegram mở bot → bấm Start.",
    "• Hoặc gõ: /start GAS-XXXXXXXX",
    "• Thấy menu nhân viên → kích hoạt xong.",
    "",
    "━━ 2. MENU (gõ /nhan_vien) ━━",
    "📋 Xem đơn — đơn đã giao cho bạn, bấm Giao hàng để hoàn thành.",
    "📥 Nhận đơn — lấy đơn chưa ai nhận (đang bổ sung).",
    "💰 Kiểm tra công nợ — xem khách nợ bao nhiêu (chỉ xem, không thu tiền).",
    "❓ Trợ giúp — đọc hướng dẫn này.",
    "",
    "━━ 3. GIAO HÀNG — TỪNG BƯỚC ━━",
    "① 📋 Xem đơn → chọn khách",
    "② Bấm 🚚 Giao hàng",
    "③ Nhập kết quả giao theo cú pháp:",
    "",
    "Một loại bình:",
    "  <vỏ thu> <tiền>vnd <tm|ck|no>",
    "  VD thu tiền mặt: 3 800000vnd tm",
    "  VD ghi nợ: 3 0vnd no",
    "",
    "Nhiều loại bình — vỏ thu từng dòng rồi tiền:",
    "  VD: 4 3 1500000vnd tm",
    "  (dòng1 thu 4 vỏ, dòng2 thu 3 vỏ, thu 1,5tr tiền mặt)",
    "",
    "  tm = tiền mặt | ck = chuyển khoản | no = ghi nợ (0đ)",
    "",
    "④ Bot hiện bảng xác nhận → bấm ✅ Hoàn thành.",
    "",
    "━━ 4. LƯU Ý ━━",
    "• Thu nợ khách: chủ đại lý làm — NV không thu trên bot.",
    "• Đơn đã gán cho bạn — người khác không nhận được.",
    "• Sai số liệu: báo chủ trong 24h để sửa trên web.",
    "",
    "━━ 5. LỆNH NHANH ━━",
    "/nhan_vien — mở menu NV",
    "/no tên hoặc SĐT — tra nợ nhanh",
    "/help — xem lại hướng dẫn",
  ].join("\n");
}

export function buildGuestHelpText(): string {
  return [
    "📖 HƯỚNG DẪN — CHƯA KÍCH HOẠT",
    "",
    "Bạn chưa vào được hệ thống GasOS.",
    "",
    "━━ CHỦ ĐẠI LÝ ━━",
    "Nhận mã mời GAS-XXXXXXXX → gõ:",
    "/start GAS-XXXXXXXX",
    "",
    "━━ NHÂN VIÊN ━━",
    "Nhờ chủ gửi link mời → bấm Start trong Telegram.",
    "Hoặc gõ /start kèm mã mời.",
    "",
    "Sau kích hoạt:",
    "• Chủ: /menu_admin",
    "• NV: /nhan_vien",
  ].join("\n");
}

export function buildHelpText(role?: string): string {
  if (role === "owner") return buildOwnerHelpText();
  if (role === "employee") return buildEmployeeHelpText();
  return buildGuestHelpText();
}
